export type IconSize = 12 | 16 | 24 | 32

export type IconName =
  | 'Alarm clock'
  | 'Bag 1'
  | 'Bag 2'
  | 'Bag 3'
  | 'Balance'
  | 'Bell'
  | 'Book'
  | 'Bookmark'
  | 'Box 1'
  | 'Box 2'
  | 'Browser'
  | 'Building'
  | 'Burger'
  | 'Calendar'
  | 'Call'
  | 'Call missed'
  | 'Call silent'
  | 'Calling'
  | 'Camera'
  | 'Cart'
  | 'Cart2'
  | 'Case'
  | 'Category'
  | 'Category2'
  | 'Chart'
  | 'Chart 1'
  | 'Check 1'
  | 'Check 2'
  | 'Close'
  | 'Close 1'
  | 'Close 2'
  | 'Cloud'
  | 'Cloud download'
  | 'Cloud upload'
  | 'Coffee'
  | 'Coins'
  | 'Collapse'
  | 'Color Palette'
  | 'Comment'
  | 'Compas'
  | 'Component 1'
  | 'Copy'
  | 'Coupon 1'
  | 'Coupon 2'
  | 'Coupon 3'
  | 'Credit card'
  | 'Danger'
  | 'Delivery'
  | 'Dislike'
  | 'Dislike-filled'
  | 'Document'
  | 'Document 2'
  | 'Document 2 edit'
  | 'Document 2 edit（阿拉伯）'
  | 'Document 2（阿拉伯）'
  | 'Document add'
  | 'Document delite'
  | 'Document（阿拉伯）'
  | 'Down'
  | 'Down 2'
  | 'Down Left'
  | 'Down Right'
  | 'Down circle'
  | 'Down left circle'
  | 'Down right circle'
  | 'Down square'
  | 'Down square 2'
  | 'Download 2'
  | 'Edit 1'
  | 'Edit 2'
  | 'Expand'
  | 'Eye'
  | 'Filter'
  | 'Fire'
  | 'Flag'
  | 'Folder'
  | 'Gamepad'
  | 'Gift'
  | 'Graph'
  | 'Headphones'
  | 'Heart'
  | 'Heartbeat'
  | 'Hide'
  | 'Home'
  | 'Image'
  | 'Info circle'
  | 'Key'
  | 'Laptop'
  | 'Layers'
  | 'Left'
  | 'Left 2'
  | 'Left circle'
  | 'Left square'
  | 'Left square 2'
  | 'Lightning'
  | 'Link'
  | 'Loading'
  | 'Location'
  | 'Lock'
  | 'Lock check'
  | 'Lock open'
  | 'Lock x'
  | 'Login'
  | 'Logout'
  | 'Mail'
  | 'Message circle'
  | 'Message square'
  | 'Message topic'
  | 'Microphone'
  | 'Minus'
  | 'More'
  | 'More circle'
  | 'More square'
  | 'Mouse'
  | 'Music'
  | 'Music plate'
  | 'No sound (microphone)'
  | 'Notice'
  | 'Numcode'
  | 'Oldschool gamepad'
  | 'Order'
  | 'Paperclip'
  | 'Pause'
  | 'Play'
  | 'Plus'
  | 'Pluses'
  | 'Question circle'
  | 'RPoint'
  | 'Receipt'
  | 'Receipt（阿拉伯）'
  | 'Refresh'
  | 'Refund'
  | 'Rider'
  | 'Right'
  | 'Right 2'
  | 'Right circle'
  | 'Right square'
  | 'Right square 2'
  | 'Rocket'
  | 'Sale'
  | 'Save'
  | 'Scale'
  | 'Scanner'
  | 'Screen'
  | 'Search'
  | 'Send'
  | 'Settings'
  | 'Share'
  | 'Share2'
  | 'Shield'
  | 'Shield 1'
  | 'Shield 2'
  | 'Shield 3'
  | 'Sorter'
  | 'Spread'
  | 'Star'
  | 'Stop'
  | 'Swap'
  | 'Swap 2'
  | 'Time Circle'
  | 'Time square'
  | 'Timer'
  | 'Toggle left'
  | 'Toggle right'
  | 'Top'
  | 'Top2'
  | 'Trash can'
  | 'Up'
  | 'Up 2'
  | 'Up Left'
  | 'Up Right'
  | 'Up circle'
  | 'Up left circle'
  | 'Up right circle'
  | 'Up square'
  | 'Up square 2'
  | 'User'
  | 'Users'
  | 'Video'
  | 'Video2'
  | 'Vip'
  | 'Volume down'
  | 'Volume off 3'
  | 'Volume off 4'
  | 'Volume up'
  | 'Wallet'
  | 'Zoom in'
  | 'Zoom out'
  | 'circle-Check'
  | 'circle-Close'
  | 'circle-Minus'
  | 'circle-Plus'
  | 'iPhone'
  | 'like'
  | 'like-filled'
  | 'locate'
  | 'widget'
  | 'Сalculator 1'
  | 'Сalculator 2'
